---
- name: Track successful and failed hosts
  hosts: all
  gather_facts: no
  tasks:
    # Example task that may fail on some hosts
    - name: Run a command that might fail
      ansible.builtin.command: /bin/true  # Replace with your actual task
      register: result
      ignore_errors: true

    # Add successful hosts to in-memory group
    - name: Add successful hosts to in-memory group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: successful_hosts
      when: result is not failed
      loop: "{{ ansible_play_hosts }}"

    # Add failed hosts to in-memory group
    - name: Add failed hosts to in-memory group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: failed_hosts
      when: result is failed
      loop: "{{ ansible_play_hosts }}"

- name: Save and report host lists
  hosts: localhost
  gather_facts: no
  tasks:
    # Save successful hosts as a fact
    - name: Set successful hosts fact
      ansible.builtin.set_fact:
        successful_hosts_list: "{{ groups['successful_hosts'] | default([]) | join(', ') }}"
        cacheable: yes

    # Save failed hosts as a fact
    - name: Set failed hosts fact
      ansible.builtin.set_fact:
        failed_hosts_list: "{{ groups['failed_hosts'] | default([]) | join(', ') }}"
        cacheable: yes

    # Save lists to files (optional, for persistence)
    #- name: Write successful hosts to a file
    #  ansible.builtin.copy:
    #  content: "{{ groups['successful_hosts'] | default([]) | join('\n') }}"
    #  dest: /tmp/successful_hosts.txt
    #when: groups['successful_hosts'] is defined

          #- name: Write failed hosts to a file
          #  ansible.builtin.copy:
          #    content: "{{ groups['failed_hosts'] | default([]) | join('\n') }}"
          #     dest: /tmp/failed_hosts.txt
          #  when: groups['failed_hosts'] is defined

    # Store lists in job stats for notification
    - name: Set job stats for notification
      ansible.builtin.set_stats:
        data:
          successful_hosts: "{{ groups['successful_hosts'] | default([]) | join(', ') }}"
          failed_hosts: "{{ groups['failed_hosts'] | default([]) | join(', ') }}"
      run_once: true
