---
- name: Test host statuses
  hosts: all
  tasks:
    - name: Succeed on some hosts
      ansible.builtin.command: /bin/true
      when: inventory_hostname in ['managedhost1.khurley.local', 'resources4exam.khurley.local']

    - name: Fail on some hosts
      ansible.builtin.command: /bin/false
      when: inventory_hostname in ['host3.example.com', 'host4.example.com']
      ignore_errors: yes

    - name: Collect succeeded hosts
      ansible.builtin.set_stats:
        data:
          succeeded_hosts: "{{ ansible_play_hosts_all | difference(ansible_failed_hosts | default([])) | list }}"

    - name: Collect failed hosts
      ansible.builtin.set_stats:
        data:
          failed_hosts: "{{ ansible_failed_hosts | default([]) | list }}"
