---
- name: Test host statuses
  hosts: all
  tasks:
    - name: Debug inventory hosts
      ansible.builtin.debug:
        msg: "Running on host: {{ inventory_hostname }}, All hosts: {{ ansible_play_hosts_all }}"

    - name: Succeed on some hosts
      ansible.builtin.command: /bin/true
      when: inventory_hostname in ansible_play_hosts_all  # Run on all hosts for testing
      register: success_result

    - name: Fail on some hosts
      ansible.builtin.command: /bin/false
      when: inventory_hostname in ansible_play_hosts_all  # Run on all hosts for testing
      ignore_errors: yes
      register: fail_result

    - name: Collect succeeded hosts
      ansible.builtin.set_stats:
        data:
          succeeded_hosts: "{{ ansible_play_hosts_all | difference(ansible_failed_hosts | default([])) | list }}"

    - name: Collect failed hosts
      ansible.builtin.set_stats:
        data:
          failed_hosts: "{{ ansible_failed_hosts | default([]) | list }}"

    - name: Debug artifacts
      ansible.builtin.debug:
        msg: "Artifacts: {{ ansible_facts.set_stats_data | default({}) }}"
